// Copyright (c) 2026 Tom Papaioannou. All rights reserved.
// Licensed under the MIT License

// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballOpenServer.Migrations
{
    [DbContext(typeof(FootballDbContext))]
    [Migration("20250915220421_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballOpenServer.Models.Tournaments.Tournament", b =>
                {
                    b.Property<Guid>("TournamentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("TournamentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TournamentTeamsType")
                        .HasColumnType("int");

                    b.Property<int>("TournamentType")
                        .HasColumnType("int");

                    b.HasKey("TournamentID");

                    b.HasIndex("ParentID");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Tournaments.TournamentParent", b =>
                {
                    b.Property<Guid>("TournamentParentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfCups")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfLeagues")
                        .HasColumnType("int");

                    b.Property<int>("TournamentParentType")
                        .HasColumnType("int");

                    b.HasKey("TournamentParentID");

                    b.ToTable("TournamentParents");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Tournaments.Tournament", b =>
                {
                    b.HasOne("FootballOpenServer.Models.Tournaments.TournamentParent", "TournamentParent")
                        .WithMany()
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TournamentParent");
                });
#pragma warning restore 612, 618
        }
    }
}
