// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballOpenServer.Migrations
{
    [DbContext(typeof(FootballDbContext))]
    [Migration("20260311183956_AddUserOwnerToTeams")]
    partial class AddUserOwnerToTeams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompetitionTeam", b =>
                {
                    b.Property<Guid>("CompetitionsCompetitionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamsTeamID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompetitionsCompetitionID", "TeamsTeamID");

                    b.HasIndex("TeamsTeamID");

                    b.ToTable("CompetitionTeam");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Competitions.Competition", b =>
                {
                    b.Property<Guid>("CompetitionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompetitionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompetitionTeamsType")
                        .HasColumnType("int");

                    b.Property<int>("CompetitionType")
                        .HasColumnType("int");

                    b.Property<Guid?>("ContinentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid?>("ServerID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompetitionID");

                    b.HasIndex("ContinentID");

                    b.HasIndex("NationID");

                    b.HasIndex("ServerID");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Contracts.Contract", b =>
                {
                    b.Property<Guid>("ContractID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TeamID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ContractID");

                    b.HasIndex("PersonID");

                    b.HasIndex("TeamID");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Matches.Match", b =>
                {
                    b.Property<Guid>("MatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("AwayGoals")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("AwayTeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("HomeGoals")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("HomeTeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartingTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("WeatherCondition")
                        .HasColumnType("int");

                    b.Property<Guid?>("WinnerTeamID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MatchID");

                    b.HasIndex("AwayTeamID");

                    b.HasIndex("HomeTeamID");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Matches.MatchEvent", b =>
                {
                    b.Property<Guid>("MatchEventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("AddedMinute")
                        .HasColumnType("tinyint");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<Guid>("MatchID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Minute")
                        .HasColumnType("smallint");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<Guid?>("PlayerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedPlayerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MatchEventID");

                    b.HasIndex("MatchID", "TeamID");

                    b.HasIndex("MatchID", "Period", "Minute", "AddedMinute", "SortOrder");

                    b.ToTable("MatchesEvents");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Matches.MatchStats", b =>
                {
                    b.Property<Guid>("MatchStatsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("AwayCorners")
                        .HasColumnType("tinyint");

                    b.Property<byte>("AwayFouls")
                        .HasColumnType("tinyint");

                    b.Property<byte>("AwayPossession")
                        .HasColumnType("tinyint");

                    b.Property<byte>("AwayRedCards")
                        .HasColumnType("tinyint");

                    b.Property<byte>("AwayShots")
                        .HasColumnType("tinyint");

                    b.Property<byte>("AwayShotsOnTarget")
                        .HasColumnType("tinyint");

                    b.Property<byte>("AwayYellowCards")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HomeCorners")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HomeFouls")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HomePossession")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HomeRedCards")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HomeShots")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HomeShotsOnTarget")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HomeYellowCards")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("MatchID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MatchStatsID");

                    b.HasIndex("MatchID")
                        .IsUnique();

                    b.ToTable("MatchesStats");
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.Person", b =>
                {
                    b.Property<Guid>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ServerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonID");

                    b.HasIndex("NationID");

                    b.HasIndex("ServerID");

                    b.ToTable("People");
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.Player", b =>
                {
                    b.Property<Guid>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlayerID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.PlayerStats", b =>
                {
                    b.Property<Guid>("PlayerStatsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Acceleration")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Control")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Creativity")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Crossing")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Decisions")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Dribbling")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Goalkeeping")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Jumping")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Kicking")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Passing")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("PlayerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Positioning")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Shooting")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Speed")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Stamina")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Strength")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Tackling")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Teamwork")
                        .HasColumnType("tinyint");

                    b.HasKey("PlayerStatsID");

                    b.HasIndex("PlayerID")
                        .IsUnique();

                    b.ToTable("PlayerStats");
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.PlayerTrainedPosition", b =>
                {
                    b.Property<Guid>("PlayerTrainedPositionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayerPosition")
                        .HasColumnType("int");

                    b.Property<byte>("PlayerTrainedPositionAdaptation")
                        .HasColumnType("tinyint");

                    b.HasKey("PlayerTrainedPositionID");

                    b.HasIndex("PlayerID");

                    b.ToTable("PlayerTrainedPositions");
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.PlayerTrainedRole", b =>
                {
                    b.Property<Guid>("PlayerTrainedRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayerPosition")
                        .HasColumnType("int");

                    b.Property<int>("PlayerRole")
                        .HasColumnType("int");

                    b.Property<byte>("PlayerTrainedRoleAdaptation")
                        .HasColumnType("tinyint");

                    b.HasKey("PlayerTrainedRoleID");

                    b.HasIndex("PlayerID");

                    b.ToTable("PlayerTrainedRoles");
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.Staff", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffID"));

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StaffRole")
                        .HasColumnType("int");

                    b.HasKey("StaffID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Servers.Server", b =>
                {
                    b.Property<Guid>("ServerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServerID");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Teams.PlayerTactic", b =>
                {
                    b.Property<Guid>("PlayerTacticID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayerPosition")
                        .HasColumnType("int");

                    b.Property<int>("PlayerRole")
                        .HasColumnType("int");

                    b.Property<Guid>("TacticID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlayerTacticID");

                    b.HasIndex("PlayerID");

                    b.ToTable("PlayerTactics");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Teams.Tactic", b =>
                {
                    b.Property<Guid>("TacticID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Formation")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isMain")
                        .HasColumnType("bit");

                    b.HasKey("TacticID");

                    b.HasIndex("TeamID");

                    b.ToTable("Tactics");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Teams.Team", b =>
                {
                    b.Property<Guid>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamID");

                    b.HasIndex("AppUserID")
                        .IsUnique()
                        .HasFilter("[AppUserID] IS NOT NULL");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Users.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid?>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PersonID")
                        .IsUnique()
                        .HasFilter("[PersonID] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Users.AppUserClaim", b =>
                {
                    b.Property<Guid>("AppUserClaimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AppUserClaimID");

                    b.HasIndex("AppUserID");

                    b.ToTable("AppUserClaims");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefreshTokenID");

                    b.HasIndex("AppUserID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("FootballOpenServer.Models.World.Continent", b =>
                {
                    b.Property<Guid>("ContinentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SymbolUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContinentID");

                    b.ToTable("Continents");
                });

            modelBuilder.Entity("FootballOpenServer.Models.World.Nation", b =>
                {
                    b.Property<Guid>("NationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContinentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FlagUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISO2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISO3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NationID");

                    b.HasIndex("ContinentID");

                    b.ToTable("Nations");
                });

            modelBuilder.Entity("CompetitionTeam", b =>
                {
                    b.HasOne("FootballOpenServer.Models.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionsCompetitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballOpenServer.Models.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsTeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballOpenServer.Models.Competitions.Competition", b =>
                {
                    b.HasOne("FootballOpenServer.Models.World.Continent", "Continent")
                        .WithMany()
                        .HasForeignKey("ContinentID");

                    b.HasOne("FootballOpenServer.Models.World.Nation", "Nation")
                        .WithMany()
                        .HasForeignKey("NationID");

                    b.HasOne("FootballOpenServer.Models.Servers.Server", "Server")
                        .WithMany("Competitions")
                        .HasForeignKey("ServerID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Continent");

                    b.Navigation("Nation");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Contracts.Contract", b =>
                {
                    b.HasOne("FootballOpenServer.Models.People.Person", "Person")
                        .WithMany("Contracts")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballOpenServer.Models.Teams.Team", "Team")
                        .WithMany("Contracts")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Matches.Match", b =>
                {
                    b.HasOne("FootballOpenServer.Models.Teams.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballOpenServer.Models.Teams.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Matches.MatchEvent", b =>
                {
                    b.HasOne("FootballOpenServer.Models.Matches.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Matches.MatchStats", b =>
                {
                    b.HasOne("FootballOpenServer.Models.Matches.Match", "Match")
                        .WithOne()
                        .HasForeignKey("FootballOpenServer.Models.Matches.MatchStats", "MatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.Person", b =>
                {
                    b.HasOne("FootballOpenServer.Models.World.Nation", "Nation")
                        .WithMany()
                        .HasForeignKey("NationID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FootballOpenServer.Models.Servers.Server", "Server")
                        .WithMany("Persons")
                        .HasForeignKey("ServerID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Nation");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.Player", b =>
                {
                    b.HasOne("FootballOpenServer.Models.People.Person", "Person")
                        .WithOne("Player")
                        .HasForeignKey("FootballOpenServer.Models.People.Player", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.PlayerStats", b =>
                {
                    b.HasOne("FootballOpenServer.Models.People.Player", "Player")
                        .WithOne("PlayerStats")
                        .HasForeignKey("FootballOpenServer.Models.People.PlayerStats", "PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.PlayerTrainedPosition", b =>
                {
                    b.HasOne("FootballOpenServer.Models.People.Player", null)
                        .WithMany("PlayerTrainedPositions")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.PlayerTrainedRole", b =>
                {
                    b.HasOne("FootballOpenServer.Models.People.Player", null)
                        .WithMany("PlayerTrainedRoles")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.Staff", b =>
                {
                    b.HasOne("FootballOpenServer.Models.People.Person", "Person")
                        .WithOne("Staff")
                        .HasForeignKey("FootballOpenServer.Models.People.Staff", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Teams.PlayerTactic", b =>
                {
                    b.HasOne("FootballOpenServer.Models.People.Player", "Player")
                        .WithMany("PlayerTactics")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Teams.Tactic", b =>
                {
                    b.HasOne("FootballOpenServer.Models.Teams.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Teams.Team", b =>
                {
                    b.HasOne("FootballOpenServer.Models.Users.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Users.AppUser", b =>
                {
                    b.HasOne("FootballOpenServer.Models.People.Person", "Person")
                        .WithOne("AppUser")
                        .HasForeignKey("FootballOpenServer.Models.Users.AppUser", "PersonID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Users.AppUserClaim", b =>
                {
                    b.HasOne("FootballOpenServer.Models.Users.AppUser", "AppUser")
                        .WithMany("Claims")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Users.RefreshToken", b =>
                {
                    b.HasOne("FootballOpenServer.Models.Users.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("FootballOpenServer.Models.World.Nation", b =>
                {
                    b.HasOne("FootballOpenServer.Models.World.Continent", "Continent")
                        .WithMany("Nations")
                        .HasForeignKey("ContinentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Continent");
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.Person", b =>
                {
                    b.Navigation("AppUser");

                    b.Navigation("Contracts");

                    b.Navigation("Player");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.Player", b =>
                {
                    b.Navigation("PlayerStats");

                    b.Navigation("PlayerTactics");

                    b.Navigation("PlayerTrainedPositions");

                    b.Navigation("PlayerTrainedRoles");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Servers.Server", b =>
                {
                    b.Navigation("Competitions");

                    b.Navigation("Persons");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Teams.Team", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Users.AppUser", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("FootballOpenServer.Models.World.Continent", b =>
                {
                    b.Navigation("Nations");
                });
#pragma warning restore 612, 618
        }
    }
}
