// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballOpenServer.Migrations
{
    [DbContext(typeof(FootballDbContext))]
    [Migration("20260627102201_AddCupMatches")]
    partial class AddCupMatches
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompetitionTeam", b =>
                {
                    b.Property<Guid>("CompetitionsCompetitionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamsTeamID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompetitionsCompetitionID", "TeamsTeamID");

                    b.HasIndex("TeamsTeamID");

                    b.ToTable("CompetitionTeam");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Competitions.Competition", b =>
                {
                    b.Property<Guid>("CompetitionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompetitionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompetitionTeamsType")
                        .HasColumnType("int");

                    b.Property<int>("CompetitionType")
                        .HasColumnType("int");

                    b.Property<Guid?>("ContinentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid?>("ServerID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompetitionID");

                    b.HasIndex("ContinentID");

                    b.HasIndex("NationID");

                    b.HasIndex("ServerID");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Competitions.CompetitionTable", b =>
                {
                    b.Property<Guid>("CompetitionTableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Draws")
                        .HasColumnType("int");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("int");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("int");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("RedCards")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.Property<int>("YellowCards")
                        .HasColumnType("int");

                    b.HasKey("CompetitionTableID");

                    b.ToTable("CompetitionTables");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Competitions.CupRound", b =>
                {
                    b.Property<Guid>("CupRoundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<int>("RoundType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeamCount")
                        .HasColumnType("int");

                    b.HasKey("CupRoundID");

                    b.HasIndex("CompetitionID", "RoundNumber")
                        .IsUnique();

                    b.ToTable("CupRounds");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Competitions.CupTie", b =>
                {
                    b.Property<Guid>("CupTieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AdvancesAsHomeTeam")
                        .HasColumnType("bit");

                    b.Property<Guid?>("AwayTeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CupRoundID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HomeTeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("NextCupTieID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TieNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("WinnerTeamID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CupTieID");

                    b.HasIndex("NextCupTieID");

                    b.HasIndex("CupRoundID", "TieNumber")
                        .IsUnique();

                    b.ToTable("CupTies");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Contracts.Contract", b =>
                {
                    b.Property<Guid>("ContractID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<byte?>("ShirtNumber")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Wage")
                        .HasColumnType("int");

                    b.HasKey("ContractID");

                    b.HasIndex("PersonID");

                    b.HasIndex("TeamID");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.Person", b =>
                {
                    b.Property<Guid>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ServerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("StaffRole")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("PersonID");

                    b.HasIndex("NationID");

                    b.HasIndex("ServerID");

                    b.ToTable("People");
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.PersonHealthAndFitness", b =>
                {
                    b.Property<Guid>("PersonHealthAndFitnessID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HealthStatus")
                        .HasColumnType("int");

                    b.Property<int>("MentalCondition")
                        .HasColumnType("int");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PhysicalCondition")
                        .HasColumnType("int");

                    b.HasKey("PersonHealthAndFitnessID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.ToTable("PersonHealthAndFitnesses");
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.PlayerStats", b =>
                {
                    b.Property<Guid>("PlayerStatsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Acceleration")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Control")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Creativity")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Crossing")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Decisions")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Dribbling")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Goalkeeping")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Jumping")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Kicking")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Passing")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Positioning")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Shooting")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Speed")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Stamina")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Strength")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Tackling")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Teamwork")
                        .HasColumnType("tinyint");

                    b.HasKey("PlayerStatsID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.ToTable("PlayerStats");
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.PlayerTrainedPosition", b =>
                {
                    b.Property<Guid>("PlayerTrainedPositionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayerPosition")
                        .HasColumnType("int");

                    b.Property<byte>("PlayerTrainedPositionAdaptation")
                        .HasColumnType("tinyint");

                    b.HasKey("PlayerTrainedPositionID");

                    b.HasIndex("PersonID");

                    b.ToTable("PlayerTrainedPositions");
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.PlayerTrainedRole", b =>
                {
                    b.Property<Guid>("PlayerTrainedRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayerPosition")
                        .HasColumnType("int");

                    b.Property<int>("PlayerRole")
                        .HasColumnType("int");

                    b.Property<byte>("PlayerTrainedRoleAdaptation")
                        .HasColumnType("tinyint");

                    b.HasKey("PlayerTrainedRoleID");

                    b.HasIndex("PersonID");

                    b.ToTable("PlayerTrainedRoles");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Servers.Server", b =>
                {
                    b.Property<Guid>("ServerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.HasKey("ServerID");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Teams.Kit", b =>
                {
                    b.Property<Guid>("KitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AwayShirtColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AwayShortsColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeShirtColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeShortsColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KitID");

                    b.ToTable("Kits");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Teams.PlayerTactic", b =>
                {
                    b.Property<Guid>("PlayerTacticID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayerPosition")
                        .HasColumnType("int");

                    b.Property<int>("PlayerRole")
                        .HasColumnType("int");

                    b.Property<int>("SquadUnit")
                        .HasColumnType("int");

                    b.Property<int?>("SubstituteOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("TacticID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlayerTacticID");

                    b.HasIndex("PersonID");

                    b.ToTable("PlayerTactics");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Teams.Stadium", b =>
                {
                    b.Property<Guid>("StadiumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StadiumState")
                        .HasColumnType("int");

                    b.HasKey("StadiumID");

                    b.ToTable("Stadium");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Teams.Tactic", b =>
                {
                    b.Property<Guid>("TacticID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CaptainID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Formation")
                        .HasColumnType("int");

                    b.Property<Guid?>("LeftCornerTakerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LeftFreeKickTakerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("PassingMentality")
                        .HasColumnType("int");

                    b.Property<Guid?>("PenaltyTakerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RightCornerTakerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RightFreeKickTakerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TacticMentality")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isMain")
                        .HasColumnType("bit");

                    b.HasKey("TacticID");

                    b.HasIndex("TeamID");

                    b.ToTable("Tactics");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Teams.Team", b =>
                {
                    b.Property<Guid>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("KitID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StadiumID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TeamID");

                    b.HasIndex("AppUserID")
                        .IsUnique()
                        .HasFilter("[AppUserID] IS NOT NULL");

                    b.HasIndex("KitID")
                        .IsUnique();

                    b.HasIndex("StadiumID")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Users.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid?>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PersonID")
                        .IsUnique()
                        .HasFilter("[PersonID] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Users.AppUserClaim", b =>
                {
                    b.Property<Guid>("AppUserClaimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AppUserClaimID");

                    b.HasIndex("AppUserID");

                    b.ToTable("AppUserClaims");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefreshTokenID");

                    b.HasIndex("AppUserID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("FootballOpenServer.Models.World.Continent", b =>
                {
                    b.Property<Guid>("ContinentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SymbolUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContinentID");

                    b.ToTable("Continents");
                });

            modelBuilder.Entity("FootballOpenServer.Models.World.Nation", b =>
                {
                    b.Property<Guid>("NationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContinentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FlagUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISO2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISO3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NationID");

                    b.HasIndex("ContinentID");

                    b.ToTable("Nations");
                });

            modelBuilder.Entity("CompetitionTeam", b =>
                {
                    b.HasOne("FootballOpenServer.Models.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionsCompetitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballOpenServer.Models.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsTeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballOpenServer.Models.Competitions.Competition", b =>
                {
                    b.HasOne("FootballOpenServer.Models.World.Continent", "Continent")
                        .WithMany()
                        .HasForeignKey("ContinentID");

                    b.HasOne("FootballOpenServer.Models.World.Nation", "Nation")
                        .WithMany()
                        .HasForeignKey("NationID");

                    b.HasOne("FootballOpenServer.Models.Servers.Server", "Server")
                        .WithMany("Competitions")
                        .HasForeignKey("ServerID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Continent");

                    b.Navigation("Nation");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Competitions.CupRound", b =>
                {
                    b.HasOne("FootballOpenServer.Models.Competitions.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Competitions.CupTie", b =>
                {
                    b.HasOne("FootballOpenServer.Models.Competitions.CupRound", "CupRound")
                        .WithMany("Ties")
                        .HasForeignKey("CupRoundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballOpenServer.Models.Competitions.CupTie", null)
                        .WithMany()
                        .HasForeignKey("NextCupTieID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CupRound");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Contracts.Contract", b =>
                {
                    b.HasOne("FootballOpenServer.Models.People.Person", "Person")
                        .WithMany("Contracts")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballOpenServer.Models.Teams.Team", "Team")
                        .WithMany("Contracts")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.Person", b =>
                {
                    b.HasOne("FootballOpenServer.Models.World.Nation", "Nation")
                        .WithMany()
                        .HasForeignKey("NationID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FootballOpenServer.Models.Servers.Server", "Server")
                        .WithMany("Persons")
                        .HasForeignKey("ServerID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Nation");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.PersonHealthAndFitness", b =>
                {
                    b.HasOne("FootballOpenServer.Models.People.Person", "Person")
                        .WithOne("HealthAndFitness")
                        .HasForeignKey("FootballOpenServer.Models.People.PersonHealthAndFitness", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.PlayerStats", b =>
                {
                    b.HasOne("FootballOpenServer.Models.People.Person", "Person")
                        .WithOne("PlayerStats")
                        .HasForeignKey("FootballOpenServer.Models.People.PlayerStats", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.PlayerTrainedPosition", b =>
                {
                    b.HasOne("FootballOpenServer.Models.People.Person", null)
                        .WithMany("PlayerTrainedPositions")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.PlayerTrainedRole", b =>
                {
                    b.HasOne("FootballOpenServer.Models.People.Person", null)
                        .WithMany("PlayerTrainedRoles")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballOpenServer.Models.Teams.PlayerTactic", b =>
                {
                    b.HasOne("FootballOpenServer.Models.People.Person", "Person")
                        .WithMany("PlayerTactics")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Teams.Tactic", b =>
                {
                    b.HasOne("FootballOpenServer.Models.Teams.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Teams.Team", b =>
                {
                    b.HasOne("FootballOpenServer.Models.Users.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FootballOpenServer.Models.Teams.Kit", "Kit")
                        .WithOne("Team")
                        .HasForeignKey("FootballOpenServer.Models.Teams.Team", "KitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballOpenServer.Models.Teams.Stadium", "Stadium")
                        .WithOne("Team")
                        .HasForeignKey("FootballOpenServer.Models.Teams.Team", "StadiumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Kit");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Users.AppUser", b =>
                {
                    b.HasOne("FootballOpenServer.Models.People.Person", "Person")
                        .WithOne("AppUser")
                        .HasForeignKey("FootballOpenServer.Models.Users.AppUser", "PersonID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Users.AppUserClaim", b =>
                {
                    b.HasOne("FootballOpenServer.Models.Users.AppUser", "AppUser")
                        .WithMany("Claims")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Users.RefreshToken", b =>
                {
                    b.HasOne("FootballOpenServer.Models.Users.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("FootballOpenServer.Models.World.Nation", b =>
                {
                    b.HasOne("FootballOpenServer.Models.World.Continent", "Continent")
                        .WithMany("Nations")
                        .HasForeignKey("ContinentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Continent");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Competitions.CupRound", b =>
                {
                    b.Navigation("Ties");
                });

            modelBuilder.Entity("FootballOpenServer.Models.People.Person", b =>
                {
                    b.Navigation("AppUser");

                    b.Navigation("Contracts");

                    b.Navigation("HealthAndFitness");

                    b.Navigation("PlayerStats");

                    b.Navigation("PlayerTactics");

                    b.Navigation("PlayerTrainedPositions");

                    b.Navigation("PlayerTrainedRoles");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Servers.Server", b =>
                {
                    b.Navigation("Competitions");

                    b.Navigation("Persons");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Teams.Kit", b =>
                {
                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Teams.Stadium", b =>
                {
                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Teams.Team", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("FootballOpenServer.Models.Users.AppUser", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("FootballOpenServer.Models.World.Continent", b =>
                {
                    b.Navigation("Nations");
                });
#pragma warning restore 612, 618
        }
    }
}
