// Copyright (c) 2026 Tom Papaioannou. All rights reserved.
// Licensed under the MIT License

// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SoccerOpenServer.Migrations
{
    [DbContext(typeof(SoccerDbContext))]
    [Migration("20251009185610_AddContracts")]
    partial class AddContracts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.Contract", b =>
                {
                    b.Property<Guid>("ContractID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TeamID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ContractID");

                    b.HasIndex("TeamID");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.Team", b =>
                {
                    b.Property<Guid>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Tournaments.Tournament", b =>
                {
                    b.Property<Guid>("TournamentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("TournamentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TournamentTeamsType")
                        .HasColumnType("int");

                    b.Property<int>("TournamentType")
                        .HasColumnType("int");

                    b.HasKey("TournamentID");

                    b.HasIndex("ParentID");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Tournaments.TournamentParent", b =>
                {
                    b.Property<Guid>("TournamentParentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NationalTeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberOfCups")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfLeagues")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfNationalCups")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfNationalLeagues")
                        .HasColumnType("int");

                    b.Property<int>("TournamentParentType")
                        .HasColumnType("int");

                    b.HasKey("TournamentParentID");

                    b.ToTable("TournamentParents");
                });

            modelBuilder.Entity("TeamTournament", b =>
                {
                    b.Property<Guid>("TeamsTeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TournamentsTournamentID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TeamsTeamID", "TournamentsTournamentID");

                    b.HasIndex("TournamentsTournamentID");

                    b.ToTable("TeamTournament");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.Contract", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.Teams.Team", null)
                        .WithMany("Contracts")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Tournaments.Tournament", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.Tournaments.TournamentParent", "TournamentParent")
                        .WithMany()
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TournamentParent");
                });

            modelBuilder.Entity("TeamTournament", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsTeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerOpenServer.Models.Tournaments.Tournament", null)
                        .WithMany()
                        .HasForeignKey("TournamentsTournamentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.Team", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
