// Copyright (c) 2026 Tom Papaioannou. All rights reserved.
// Licensed under the MIT License

// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SoccerOpenServer.Migrations
{
    [DbContext(typeof(FootballDbContext))]
    [Migration("20251102104429_AddTactics")]
    partial class AddTactics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoccerOpenServer.Models.Contracts.Contract", b =>
                {
                    b.Property<Guid>("ContractID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TeamID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ContractID");

                    b.HasIndex("TeamID");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.Person", b =>
                {
                    b.Property<Guid>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContractID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonID");

                    b.ToTable("People");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.Player", b =>
                {
                    b.Property<Guid>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlayerID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.PlayerTrainedPosition", b =>
                {
                    b.Property<Guid>("PlayerTrainedPositionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayerPosition")
                        .HasColumnType("int");

                    b.HasKey("PlayerTrainedPositionID");

                    b.ToTable("PlayerTrainedPositions");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.PlayerTrainedRole", b =>
                {
                    b.Property<Guid>("PlayerTrainedRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayerPosition")
                        .HasColumnType("int");

                    b.Property<int>("PlayerRole")
                        .HasColumnType("int");

                    b.HasKey("PlayerTrainedRoleID");

                    b.ToTable("PlayerTrainedRoles");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.PlayerTactic", b =>
                {
                    b.Property<Guid>("PlayerTacticID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayerPosition")
                        .HasColumnType("int");

                    b.Property<int>("PlayerRole")
                        .HasColumnType("int");

                    b.Property<Guid>("TacticID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlayerTacticID");

                    b.ToTable("PlayerTactics");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.Tactic", b =>
                {
                    b.Property<Guid>("TacticID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isMain")
                        .HasColumnType("bit");

                    b.HasKey("TacticID");

                    b.HasIndex("TeamID");

                    b.ToTable("Tactics");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.Team", b =>
                {
                    b.Property<Guid>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Tournaments.Tournament", b =>
                {
                    b.Property<Guid>("TournamentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("TournamentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TournamentTeamsType")
                        .HasColumnType("int");

                    b.Property<int>("TournamentType")
                        .HasColumnType("int");

                    b.HasKey("TournamentID");

                    b.HasIndex("ParentID");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Tournaments.TournamentParent", b =>
                {
                    b.Property<Guid>("TournamentParentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NationalTeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberOfCups")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfLeagues")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfNationalCups")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfNationalLeagues")
                        .HasColumnType("int");

                    b.Property<int>("TournamentParentType")
                        .HasColumnType("int");

                    b.HasKey("TournamentParentID");

                    b.ToTable("TournamentParents");
                });

            modelBuilder.Entity("TeamTournament", b =>
                {
                    b.Property<Guid>("TeamsTeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TournamentsTournamentID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TeamsTeamID", "TournamentsTournamentID");

                    b.HasIndex("TournamentsTournamentID");

                    b.ToTable("TeamTournament");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Contracts.Contract", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.Teams.Team", null)
                        .WithMany("Contracts")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.Player", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.People.Person", "Person")
                        .WithOne("Player")
                        .HasForeignKey("SoccerOpenServer.Models.People.Player", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.Tactic", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.Teams.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Tournaments.Tournament", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.Tournaments.TournamentParent", "TournamentParent")
                        .WithMany()
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TournamentParent");
                });

            modelBuilder.Entity("TeamTournament", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsTeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerOpenServer.Models.Tournaments.Tournament", null)
                        .WithMany()
                        .HasForeignKey("TournamentsTournamentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.Person", b =>
                {
                    b.Navigation("Player");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.Team", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
