// Copyright (c) 2026 Tom Papaioannou. All rights reserved.
// Licensed under the MIT License

// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SoccerOpenServer.Migrations
{
    [DbContext(typeof(SoccerDbContext))]
    [Migration("20260129154255_AddUsersAndClaimsInDB")]
    partial class AddUsersAndClaimsInDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompetitionTeam", b =>
                {
                    b.Property<Guid>("CompetitionsCompetitionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamsTeamID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompetitionsCompetitionID", "TeamsTeamID");

                    b.HasIndex("TeamsTeamID");

                    b.ToTable("CompetitionTeam");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Competitions.Competition", b =>
                {
                    b.Property<Guid>("CompetitionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompetitionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompetitionTeamsType")
                        .HasColumnType("int");

                    b.Property<int>("CompetitionType")
                        .HasColumnType("int");

                    b.Property<Guid>("ParentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("CompetitionID");

                    b.HasIndex("ParentID");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Competitions.CompetitionParent", b =>
                {
                    b.Property<Guid>("CompetitionParentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompetitionParentType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NationalTeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberOfCups")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfLeagues")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfNationalCups")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfNationalLeagues")
                        .HasColumnType("int");

                    b.HasKey("CompetitionParentID");

                    b.ToTable("CompetitionParents");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Contracts.Contract", b =>
                {
                    b.Property<Guid>("ContractID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TeamID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ContractID");

                    b.HasIndex("TeamID");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.Person", b =>
                {
                    b.Property<Guid>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContractID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonID");

                    b.ToTable("People");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.Player", b =>
                {
                    b.Property<Guid>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlayerID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.PlayerTrainedPosition", b =>
                {
                    b.Property<Guid>("PlayerTrainedPositionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayerPosition")
                        .HasColumnType("int");

                    b.Property<int>("PlayerTrainedPositionAdaptaption")
                        .HasColumnType("int");

                    b.HasKey("PlayerTrainedPositionID");

                    b.HasIndex("PlayerID");

                    b.ToTable("PlayerTrainedPositions");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.PlayerTrainedRole", b =>
                {
                    b.Property<Guid>("PlayerTrainedRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayerPosition")
                        .HasColumnType("int");

                    b.Property<int>("PlayerRole")
                        .HasColumnType("int");

                    b.Property<int>("PlayerTrainedRoleAdaptaption")
                        .HasColumnType("int");

                    b.HasKey("PlayerTrainedRoleID");

                    b.HasIndex("PlayerID");

                    b.ToTable("PlayerTrainedRoles");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.PlayerTactic", b =>
                {
                    b.Property<Guid>("PlayerTacticID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayerPosition")
                        .HasColumnType("int");

                    b.Property<int>("PlayerRole")
                        .HasColumnType("int");

                    b.Property<Guid>("TacticID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlayerTacticID");

                    b.ToTable("PlayerTactics");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.Tactic", b =>
                {
                    b.Property<Guid>("TacticID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isMain")
                        .HasColumnType("bit");

                    b.HasKey("TacticID");

                    b.HasIndex("TeamID");

                    b.ToTable("Tactics");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.Team", b =>
                {
                    b.Property<Guid>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Users.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Users.AppUserClaim", b =>
                {
                    b.Property<Guid>("AppUserClaimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AppUserClaimID");

                    b.HasIndex("AppUserID");

                    b.ToTable("AppUserClaims");
                });

            modelBuilder.Entity("CompetitionTeam", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionsCompetitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerOpenServer.Models.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsTeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Competitions.Competition", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.Competitions.CompetitionParent", "CompetitionParent")
                        .WithMany()
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompetitionParent");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Contracts.Contract", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.Teams.Team", null)
                        .WithMany("Contracts")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.Player", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.People.Person", "Person")
                        .WithOne("Player")
                        .HasForeignKey("SoccerOpenServer.Models.People.Player", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.PlayerTrainedPosition", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.People.Player", null)
                        .WithMany("PlayerTrainedPositions")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.PlayerTrainedRole", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.People.Player", null)
                        .WithMany("PlayerTrainedRoles")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.Tactic", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.Teams.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Users.AppUserClaim", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.Users.AppUser", "AppUser")
                        .WithMany("Claims")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.Person", b =>
                {
                    b.Navigation("Player");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.Player", b =>
                {
                    b.Navigation("PlayerTrainedPositions");

                    b.Navigation("PlayerTrainedRoles");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.Team", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Users.AppUser", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
